[package]
name = "btc-rpt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoincore-rpc = "0.18.0"
bitcoincore-rpc-json = "0.18.0"
tokio = { version = "1", features = ["full"] }
